name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: docker build -t docker.pkg.github.com/sjtug/rsync-huai-docker/rsync-huai:1.0 .
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        docker push docker.pkg.github.com/sjtug/rsync-huai-docker/rsync-huai:1.0
